// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Venflow.VSIX
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVenflowVSIXPackageString = "1539ee19-e93f-4f44-810d-d30e745f4862";
        public static Guid guidVenflowVSIXPackage = new Guid(guidVenflowVSIXPackageString);

        public const string uiContextCommandSupportedFilesString = "1932ef15-1cc8-4b14-b0e6-686a73d49f59";
        public static Guid uiContextCommandSupportedFiles = new Guid(uiContextCommandSupportedFilesString);

        public const string guidVenflowVSIXPackageCmdSetString = "c2132992-6da8-4241-91c1-0ebee374c666";
        public static Guid guidVenflowVSIXPackageCmdSet = new Guid(guidVenflowVSIXPackageCmdSetString);

        public const string guidImagesString = "288b51d4-094d-400f-94d7-5e7f5301650d";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenu = 0x1010;
        public const int MyMenuGroup = 0x1020;
        public const int MigrationGroup = 0x2000;
        public const int CreateMigrationCommandId = 0x0100;
        public const int UpdateDatabaseCommandId = 0x0150;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}