name: Benchmarks

on:
  release:
    types: [created]

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        VENFLOW_BENCHMARKS_CONNECTION_STRING: 'Server=127.0.0.1;Port=5432;Database=venflow_benchmarks;UserId=venflow_benchmarks;Password=venflow_benchmarks;'

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.1.21463.6

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Configure PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13.1'
        postgresql db: 'venflow_benchmarks'
        postgresql user: 'venflow_benchmarks'
        postgresql password: 'venflow_benchmarks'

    - name: Clear old benchmarks
      working-directory: ./benchmarks
      run: rm -rf *

    - name: Run Query Benchmarks
      working-directory: ./test/Venflow.Benchmarks
      run: dotnet run -c Release -f net6.0 -- -f "*query*"

    - name: Run Insert Benchmarks
      working-directory: ./test/Venflow.Benchmarks
      run: dotnet run -c Release -f net6.0 -- -f "*insert*"

    - name: Run Update Benchmarks
      working-directory: ./test/Venflow.Benchmarks
      run: dotnet run -c Release -f net6.0 -- -f "*update*"

    - name: Run Delete Benchmarks
      working-directory: ./test/Venflow.Benchmarks
      run: dotnet run -c Release -f net6.0 -- -f "*delete*"

    - name: Run Instantiation Benchmarks
      working-directory: ./test/Venflow.Benchmarks
      run: dotnet run -c Release -f net6.0 -- -f "*instantiation*"

    - name: Run Score Calculator
      working-directory: ./test/Venflow.Score
      run: dotnet run -c Release -- "../Venflow.Benchmarks/BenchmarkDotNet.Artifacts/results" "../../../benchmarks" "../../../README.md"

    - name: Commit Benchmark changes
      uses: stefanzweifel/git-auto-commit-action@v4.13.1
      with:
        commit_message: Updated Benchmarks
        branch: dev
        push_options: '--force'
