name: .NET Core

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
        VENFLOW_TESTS_CONNECTION_STRING: 'Server=127.0.0.1;Port=5432;Database=venflow_tests;UserId=venflow_tests;Password=venflow_tests;Timeout=25;'

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-rc.1.21463.6

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.400

    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.118

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Configure PostgreSQL
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13.4'
        postgresql db: 'venflow_tests'
        postgresql user: 'venflow_tests'
        postgresql password: 'venflow_tests'

    - name: Execute Tests (.Net 6)
      working-directory: ./test/Venflow.Tests
      run: 'dotnet test -c Release --no-restore --no-build --verbosity normal -f net6.0 /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput=coverage-reports/ /p:Exclude="[Venflow.Shared]*"'

    - name: Execute Tests (.Net 5)
      working-directory: ./test/Venflow.Tests
      run: dotnet test -c Release --no-restore --no-build --verbosity normal -f net5.0

    - name: Execute Tests (.Net Core 3.1)
      working-directory: ./test/Venflow.Tests
      run: dotnet test -c Release --no-restore --no-build --verbosity normal -f netcoreapp3.1

    - name: Upload coverage report to coveralls.io
      uses: coverallsapp/github-action@master
      if: ${{ github.event_name == 'push' }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./test/Venflow.Tests/coverage-reports/coverage.net6.0.info

    - name: Build Documentation
      uses: nikeee/docfx-action@v1.0.0
      if: ${{ github.event_name == 'push' }}
      with:
        args: /github/workspace/docs/docfx/docfx.json --property TargetFramework=net5.0
        
    - name: Deploy Documentation to Github Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      if: ${{ github.event_name == 'push' }}
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: dev
        folder: docs
        target-folder: docs
        commit-message: "Updated docs"
        clean: true
